# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clean Lines"
license = "MIT"
licenselink = "https://github.com/matmunn/clean-lines/blob/master/LICENSE.md"
description = "A clean, minimal theme used for my personal site"
homepage = "http://www.matmunn.me/"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "Mat Munn"
  homepage = "http://www.matmunn.me"
